apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-stress-tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpa-stress-tool
  template:
    metadata:
      labels:
        app: hpa-stress-tool
    spec:
      containers:
      - name: hpa-stress-tool
        image: cagataykahraman/alpine-stress-tool:latest
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"
